name: ci.docker

on: workflow_dispatch

env:
  AZ_RG_NAME: 'acr-poc'
  AZ_RG_LOCATION: 'Brazil South'
  AZ_ACR_NAME: 'sampleacr022'
  
jobs:          
  build:
    runs-on: [self-hosted]
    container: 
     image: node:14.16
     volumes:
        - my_docker_volume:/volume_mount       
    steps:
      #- name: Install Azure cli
      #  run: |
      #    sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
      #    curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
      #    AZ_REPO=$(lsb_release -cs)
      #    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
      #    sudo apt-get update
      #    sudo apt-get install azure-cli
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v3
        
      # Log into Azure
      #- name: Login
      #  uses: azure/login@v1
       # with:
       #   creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      #- name: Set ACR variables
      #  run: |
       #   url_acr=$(az acr show -n ${{ env.AZ_ACR_NAME }} --query loginServer --output tsv)
       #   login_acr=$(az acr credential show -n ${{ env.AZ_ACR_NAME }} --query username --output tsv)
       #   password_acr=$(az acr credential show -n ${{ env.AZ_ACR_NAME }} --query passwords[0].value --output tsv)
       #   echo "::add-mask::$url_acr"
       #   echo "::add-mask::$login_acr"
       #   echo "::add-mask::$password_acr"
        #  echo "ACR_URL=$url_acr" >> $GITHUB_ENV
        #  echo "ACR_LOGIN=$login_acr" >> $GITHUB_ENV
        #  echo "ACR_PASSWORD=$password_acr" >> $GITHUB_ENV
          
    #  - name: Docker Login
    #    uses: docker/login-action@v1.14.1
     #   with:
     #     registry: ${{ env.ACR_URL }}
      #    username: ${{ env.ACR_LOGIN }}
     #     password: ${{ env.ACR_PASSWORD }}
      
      - name: Build and push TodoApi image
        uses: docker/build-push-action@v3
        with:
          context: src/ContainerApp.TodoApi
          file: src/ContainerApp.TodoApi/Dockerfile
          tags: latest
          push: false  
