name: ci.docker.gaia

on: workflow_dispatch

env:
  AZ_RG_NAME: 'acr-poc'
  AZ_RG_LOCATION: 'Brazil South'
  AZ_ACR_NAME: 'sampleacr022'
  
jobs:          
  build:
    runs-on: [self-hosted]
    container: 
     image: docker:23-git
     volumes:
        - my_docker_volume:/volume_mount       
    steps:
     
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v3
        
      
      - name: Build and push TodoApi image
        uses: docker/build-push-action@v3
        with:
          context: src/ContainerApp.TodoApi
          file: src/ContainerApp.TodoApi/Dockerfile
          tags: latest
          push: false  
